export const blogPosts = [
  {
    id: "service-maintenance",
    slug: "service-maintenance",
    title: "Service & Maintenance",
    category: "MAINTENANCE",
    excerpt:
      "Essential servicing requirements to keep your Deluxe Caravan in peak condition — from first service intervals to comprehensive annual checks.",
    date: "April 2024",
    sections: [
      {
        title: "First service and every 3000km service",
        note: "Should cover the below at a minimum:",
        items: [
          "Wheel bearing check and adjust",
          "Wheel nut tension",
          "Tyre pressure and wear pattern",
          "Visual inspection of suspension",
          "Visual inspection of under carriage",
          "Check brakes",
          "Check operation of external 12 Volt lights",
          "Check operation of interior lights",
          "Check operation of appliances",
          "Check for any exterior seals that show signs of deterioration or gaps that needs resealing",
          "Check adjustment of doors, windows and hatches",
          "Grease shackle and coupling nipples",
          "Remove, Clean, Inspect, Repack of wheel Bearings",
          "Inspect Drum for wearing",
          "Inspect Magnet Face for wearing",
          "Remove magnet & check for wearing on ARM & MAGNET",
          "Inspect Brake Shoes and Oil Backing Plate",
          "Inspect Bushes for Movement",
          "Grease shackle and coupling nipples",
          "Test Brake-Away",
        ],
      },
      {
        title: "Major service at 12 month or 10,000km",
        note: "Should cover the following at a minimum:",
        items: [
          "Remove, Clean, Inspect, Repack of wheel Bearings",
          "Inspect Drum for wearing",
          "Inspect Magnet Face for wearing",
          "Remove Magnet & check for wearing on ARM & MAGNET",
          "Inspect Brake Shoes and Oil Backing Plate",
          "Inspect Bushes for Movement",
          "Inspect springs & Suspension System (Shock Absorbers)",
          "Check Tyre Wear and Tyre pressures (INCLUDE SPARE/S)",
          "Check wind down legs and lubricate",
          "Check tail light etc.",
          "Grease Coupling & Adjust",
          "Adjust Hand Brake",
          "Grease shackle and coupling nipples",
          "Check Anode",
          "Run hot water Tap & Check HWS is full",
          "Check if Pump",
          "Test Brakes",
          "Check for any exterior seals that show signs of deterioration or gaps that needs resealing",
          "Check Battery Condition and Report",
        ],
      },
    ],
  },
];
